SELECT  A.NAME
	   ,A.TYPE
	   ,B.TEXT
FROM SYSOBJECTS  A (NOLOCK)
JOIN SYSCOMMENTS B (NOLOCK)  ON A.ID = B.ID
WHERE B.TEXT LIKE '%SELECT DISTINCT%'  --AND A.TYPE = 'P'                    
ORDER BY A.NAME
